### ISSUE TITLE
Crashes if no Genre selected

### ISSUE THREAD

**Issue by SJLennon** [mdn/sprints#3489]
## URL(s)

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form

## Request type

- [x] Correction or update

## Details

If you do not select a Genre check box, the code crashes.  I find it quite hard to determine where the problem actually occurs, but it is some where in the sanitizeBody('*').escape() code.  If I comment this line out, then there are no errors and the book is added.

This is the error that is shown:
ValidationError: Book validation failed: genre: Cast to [ObjectId] failed for value "[""]" at path "genre"
    at model.Document.invalidate (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\mongoose\lib\document.js:2574:32)
    at model.$set (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\mongoose\lib\document.js:1246:12)
    at model._handleIndex (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\mongoose\lib\document.js:979:14)
    at model.$set (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\mongoose\lib\document.js:920:22)
    at model.Document (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\mongoose\lib\document.js:139:12)
    at model.Model (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\mongoose\lib\model.js:107:12)
    at new model (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\mongoose\lib\model.js:4710:15)
    at exports.book_create_post (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\controllers\bookController.js:121:20)
    at Layer.handle [as handle_request] (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\express\lib\router\route.js:137:13)
    at middleware (c:\Users\Sam\Documents\Sam_tech\VSCode\express-locallibrary-tutorial\node_modules\express-validator\src\middlewares\sanitize.js:22:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Running this in VSCODE. Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
   **I'm testing using Firefox, not Chrome**

**Comment by chrisdavidmills** [comment]
Another one for @hamishwillee.

**Comment by hamishwillee** [comment]
Hi @SJLennon 

I can't reproduce this. On Ubuntu 20.04 I installed node12, cloned https://github.com/mdn/express-locallibrary-tutorial, installed the default dependencies and ran this. Created 2 books with genres and 5 without - 3 on firefox and 2 on chrome.

Did you use your own "new" database?

This uses a default database I set up a while ago "by default". This is now filled with people's test books etc. In the past there have been issues where people have modified the code and uploaded incompatible artifacts to the database. It is possible that your book accessed one of these somehow?

**Comment by SJLennon** [comment]
I definitely used my own new, shiny database.  I'm running on Win 10 and was using VSCODE for development, if that makes any difference.
It's been a while since I looked at this and I'd moved past the problem, but I'll see if I can reproduce the error over the weekend.

________________________________

**Comment by hamishwillee** [comment]
Thanks very much @SJLennon - it may also be that the issue was fixed by PR in the interim.

**Comment by SJLennon** [comment]
I've gone back in to my project and it is still crashing.

First step in the tutorial is to add this code:

	const { body,validationResult } = require('express-validator/check');
	const { sanitizeBody } = require('express-validator/filter');

That give these messages in the debug console:
_express-validator: requires to express-validator/check are deprecated.You should just use require("express-validator") instead.
express-validator: requires to express-validator/filter are deprecated.You should just use require("express-validator") instead._

So I changed the code:

    const { body, validationResult } = require('express-validator');
    const { sanitizeBody } = require('express-validator');

Debug console messages is now:
_express-validator: sanitize(), sanitizeBody() and other sanitization-only middlewares have been deprecated.
Please use check(), body() and others instead, which must offer the same API, and more._

And it still crashes.  

I'm a little confused by the code, in that _body_ and _sanitizeBody_ seem to be the same thing.  I suppose this might just be for clarity, but I'm not sure where check() and body() should be used. 

**What else can I do to assist?**

Also in the debug console is this deprecation warning which should perhaps also be fixed:

_(node:12704) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor._

**Comment by hamishwillee** [comment]
@SJLennon the last point "Also in the debug console is this deprecation warning which should perhaps also be fixed:" - I fixed that on Monday.

**Comment by hamishwillee** [comment]
@SJLennon OK, so this repo fixes its dependencies in the package.json file. If you use the latest you get the deprecation warning and crash. The fix is to either revert to package.json or in your code you can make the same updates as I have here: https://github.com/mdn/express-locallibrary-tutorial/pull/100

Essentially this removes the use of sanitzeBody - not only deprecated, but causes this crash. 

> I'm a little confused by the code, in that body and sanitizeBody seem to be the same thing. I suppose this might just be for clarity, but I'm not sure where check() and body() should be used.

that is answered by the PR linked above. Basically sanitizeBody is sanitisation middleware. The latest version deprecates this and the same functionality is in the body or check (validation) middleware. We don't use check in this code. We do use `body`. So all I had to do was add the santiization commands to the end of those changes - e.g. `.escape()`. 

This works :-). I still have to update the docs, which I will  do this afternoon. 

Thanks very much for posting and for your help.
