### ISSUE TITLE
Fix little typo in CSS hyphens page

### ISSUE THREAD

**Issue by Replica80** [mdn/sprints#3998]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the CSS property page for hyphens, there is a little fault in the Spanish version.
In the HTML example, the 3rd one is:

<p lang="enes class="auto">

And it should be:

<p lang="es" class="auto">

Besides of that, the result page just below doesn't exist.

https://developer.mozilla.org/es/docs/Web/CSS/hyphens

(I've been looking for how to edit that little typo myself, but I haven't found the way. I'm new here).

**Comment by BrewMasterMD** [comment]
Hi. This was fixed here: https://github.com/mdn/translated-content/pull/307

**Comment by caugner** [comment]
This is still an issue, transferring the issue to translated-content:

https://github.com/mdn/translated-content/blob/45fd4b7b70d4e09f568c0074c7e9091e81aa5785/files/es/web/css/hyphens/index.md#L67
